apiVersion: v1
kind: Pod
metadata:
  name: mrsoho-frontend-pod
spec:
  containers:
  - name: my-first-container
    image: sakibsakib/mrsohofrontend:latest
    ports:
    - containerPort: 5173
    resources:
      limits:
        memory: "128Mi"
        cpu: "500m"
      requests:
        memory: "64Mi"
        cpu: "250m"